In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("miadul/house-price-prediction-dataset")

print("Path to dataset files:", path)

Path to dataset files: /kaggle/input/datasets/miadul/house-price-prediction-dataset

In [2]:
import pandas as pd
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

path = "/kaggle/input/datasets/miadul/house-price-prediction-dataset/house_price_50k.csv"

df = pd.read_csv(path)

df.head()

,area,bedrooms,bathrooms,floors,age,distance,garage,parking,garden,security,school_nearby,hospital_nearby,shopping_mall_nearby,public_transport,crime_rate,population_density,location,income_level,price
0,1360,6,2,2,9,10,0,0,1,0,1,0,1,0,6.939333,7242,premium,low,5.952493e+05
1,4272,5,2,3,24,8,1,0,0,1,1,1,1,0,0.400918,7729,low,low,1.571208e+06
2,3592,1,4,3,4,20,0,1,1,1,0,1,0,1,6.292386,1081,premium,mid,1.379943e+06
3,966,5,2,2,6,14,1,0,0,0,0,1,1,0,8.964112,8912,medium,low,4.367819e+05
4,4926,4,3,1,18,9,0,0,0,0,1,0,1,1,2.843309,8146,low,mid,1.792425e+06

In [3]:
df.shape

(50000, 19)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   area                  50000 non-null  int64
 1   bedrooms              50000 non-null  int64
 2   bathrooms             50000 non-null  int64
 3   floors                50000 non-null  int64
 4   age                   50000 non-null  int64
 5   distance              50000 non-null  int64
 6   garage                50000 non-null  int64
 7   parking               50000 non-null  int64
 8   garden                50000 non-null  int64
 9   security              50000 non-null  int64
 10  school_nearby         50000 non-null  int64
 11  hospital_nearby       50000 non-null  int64
 12  shopping_mall_nearby  50000 non-null  int64
 13  public_transport      50000 non-null  int64
 14  crime_rate            50000 non-null  float64
 15  population_density    50000 non-null  int64
 16  location              50000 non-null  object
 17  income_level          50000 non-null  object
 18  price                 50000 non-null  float64
dtypes: float64(2), int64(15), object(2)
memory usage: 7.2+ MB

In [5]:
df.describe()

,area,bedrooms,bathrooms,floors,age,distance,garage,parking,garden,security,school_nearby,hospital_nearby,shopping_mall_nearby,public_transport,crime_rate,population_density,price
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.00000,5.000000e+04
mean,2752.970540,3.496040,2.498040,1.997060,19.573740,14.968700,0.500540,0.497300,0.500280,0.496220,0.501100,0.498320,0.498320,0.500040,5.006444,5065.94598,1.030261e+06
std,1297.148134,1.712146,1.117704,0.815368,11.552502,8.363714,0.500005,0.499998,0.500005,0.499991,0.500004,0.500002,0.500002,0.500005,2.876776,2864.34322,4.580199e+05
min,500.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000311,100.00000,9.090069e+04
25%,1630.000000,2.000000,1.000000,1.000000,10.000000,8.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.523018,2575.00000,6.357375e+05
50%,2756.000000,3.000000,2.000000,2.000000,20.000000,15.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000,5.022946,5060.50000,1.031763e+06
75%,3872.000000,5.000000,3.000000,3.000000,30.000000,22.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,7.479632,7543.00000,1.423102e+06
max,4999.000000,6.000000,4.000000,3.000000,39.000000,29.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,9.999869,9999.00000,1.996474e+06

In [6]:
df.columns

Index(['area', 'bedrooms', 'bathrooms', 'floors', 'age', 'distance', 'garage',
       'parking', 'garden', 'security', 'school_nearby', 'hospital_nearby',
       'shopping_mall_nearby', 'public_transport', 'crime_rate',
       'population_density', 'location', 'income_level', 'price'],
      dtype='object')

In [7]:
df.nunique()

area                     4500
bedrooms                    6
bathrooms                   4
floors                      3
age                        40
distance                   29
garage                      2
parking                     2
garden                      2
security                    2
school_nearby               2
hospital_nearby             2
shopping_mall_nearby        2
public_transport            2
crime_rate              50000
population_density       9846
location                    3
income_level                3
price                   50000
dtype: int64

In [8]:
df.isnull().sum()

area                    0
bedrooms                0
bathrooms               0
floors                  0
age                     0
distance                0
garage                  0
parking                 0
garden                  0
security                0
school_nearby           0
hospital_nearby         0
shopping_mall_nearby    0
public_transport        0
crime_rate              0
population_density      0
location                0
income_level            0
price                   0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
X = df.drop("price", axis=1)
y = df["price"]

print(X.shape)
print(y.shape)

(50000, 18)
(50000,)

In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    X,y,
    test_size=0.2,
    random_state=42
)

In [12]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(40000, 18)
(10000, 18)
(40000,)
(10000,)

In [13]:
categorical_cols = ["location", "income_level"]

preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols)
    ],
    remainder="passthrough"
)

In [14]:
model = Pipeline([
    ("preprocessor",preprocessor),
     ("regressor", RandomForestRegressor(
        n_estimators=100,
        random_state=42,
        n_jobs=-1
    )) 
])
model.fit(X_train, y_train)
print("Model training completed")

Model training completed

In [15]:
y_pred = model.predict(X_test)
print(y_pred[:10])

[ 719833.08462666  428832.34918099 1683262.28710199 1206075.74823004
 1609190.58064032 1021836.69607291 1250526.99724024  696991.86703374
 1696522.84372912  380495.72913389]

In [16]:
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("MAE :", mae)
print("RMSE:", rmse)
print("R2 Score:", r2)

MAE : 21513.14412827892
RMSE: 27012.45014923903
R2 Score: 0.9965359966341806

In [17]:
print(df.corr(numeric_only=True)["price"].sort_values(ascending=False))

price                   1.000000
area                    0.991364
bedrooms                0.047123
bathrooms               0.025626
parking                 0.015492
hospital_nearby         0.013600
population_density      0.010539
garden                  0.008736
garage                  0.004506
floors                  0.003135
security                0.001659
school_nearby          -0.000416
public_transport       -0.001022
shopping_mall_nearby   -0.003412
crime_rate             -0.016964
distance               -0.028118
age                    -0.058757
Name: price, dtype: float64

In [18]:
comparison = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred
})

print(comparison.head(10))

         Actual     Predicted
0  7.364082e+05  7.198331e+05
1  4.050467e+05  4.288323e+05
2  1.676382e+06  1.683262e+06
3  1.223010e+06  1.206076e+06
4  1.632433e+06  1.609191e+06
5  1.044790e+06  1.021837e+06
6  1.233416e+06  1.250527e+06
7  7.012497e+05  6.969919e+05
8  1.686369e+06  1.696523e+06
9  4.341471e+05  3.804957e+05

In [19]:
comparison["Error"] = comparison["Actual"] - comparison["Predicted"]

print(comparison.head(10))

         Actual     Predicted         Error
0  7.364082e+05  7.198331e+05  16575.138912
1  4.050467e+05  4.288323e+05 -23785.646241
2  1.676382e+06  1.683262e+06  -6879.949415
3  1.223010e+06  1.206076e+06  16934.592318
4  1.632433e+06  1.609191e+06  23242.508981
5  1.044790e+06  1.021837e+06  22953.190389
6  1.233416e+06  1.250527e+06 -17111.443260
7  7.012497e+05  6.969919e+05   4257.844782
8  1.686369e+06  1.696523e+06 -10153.442164
9  4.341471e+05  3.804957e+05  53651.343828

In [20]:
import joblib
joblib.dump(model,"house_price_model.pkl")
print("model saved successfully")

model saved successfully

In [21]:
import os

print(os.listdir("/kaggle/working"))

['__notebook__.ipynb', 'house_price_model.pkl']